version: '3.5'

services:
  eureka:
    image: netflixoss/eureka:1.3.1
    ports:
      - "10000:8080"

  elasticsearch:
    container_name: ms_searcher_elastic_search
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
    environment:
      xpack.security.enabled: "false"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"

  kibana:
    container_name: ms_searcher_kibana
    image: kibana:5.3.2
    ports:
      - "5601:5601"

  zookeeper:
    container_name: ms_searcher_zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"